# Generated by Django 4.1.3 on 2022-11-16 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TreeClassifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=221)),
            ],
        ),
        migrations.CreateModel(
            name='TypeTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=221)),
                ('classifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.treeclassifier')),
            ],
        ),
        migrations.CreateModel(
            name='TreeDeliveryCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=221)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.region')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_tree', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=221)),
                ('contract_number', models.CharField(max_length=30)),
                ('contract_date', models.CharField(max_length=20)),
                ('contract_file', models.FileField(upload_to='contract_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.treedeliverycompany')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.district')),
                ('type_tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.typetree')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.region'),
        ),
    ]
