# Generated by Django 4.1.3 on 2022-11-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Two'), (3, 'Three')], default=1),
        ),
    ]
