# Generated by Django 4.1.3 on 2022-11-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_trade_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='address',
        ),
        migrations.AddField(
            model_name='trade',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
