# Generated by Django 4.1.3 on 2022-11-16 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_contract', models.CharField(max_length=64)),
                ('date_contract', models.CharField(max_length=20)),
                ('number_akt', models.CharField(max_length=50)),
                ('date_akt', models.CharField(max_length=20)),
                ('company_stir', models.CharField(max_length=20)),
                ('name_company', models.CharField(max_length=300)),
                ('owner_jshshir', models.CharField(max_length=16)),
                ('owner_fio', models.CharField(max_length=221)),
                ('phone', models.CharField(max_length=15)),
                ('number_report', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contracts',
                'verbose_name_plural': 'Contracts',
            },
        ),
        migrations.CreateModel(
            name='ContractWithPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_contract', models.CharField(max_length=64)),
                ('date_contract', models.CharField(max_length=20)),
                ('number_akt', models.CharField(max_length=50)),
                ('date_akt', models.CharField(max_length=20)),
                ('company_stir', models.CharField(max_length=20)),
                ('name_company', models.CharField(max_length=300)),
                ('owner_jshshir', models.CharField(max_length=16)),
                ('owner_fio', models.CharField(max_length=221)),
                ('partner_stir', models.CharField(max_length=20)),
                ('partner_name', models.CharField(max_length=221)),
                ('partner_owner_jshshir', models.CharField(max_length=16)),
                ('partner_fio', models.CharField(max_length=221)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ContractWithPartner',
                'verbose_name_plural': 'ContractWithPartner',
            },
        ),
        migrations.CreateModel(
            name='ContractImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='contracts/')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract', verbose_name='contracts_images')),
            ],
        ),
    ]
