# Generated by Django 4.1.3 on 2022-11-19 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contract_status_contractwithpartner_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='image',
            field=models.ImageField(null=True, upload_to='contracts'),
        ),
        migrations.AddField(
            model_name='contract',
            name='image1',
            field=models.ImageField(null=True, upload_to='contracts'),
        ),
        migrations.AddField(
            model_name='contract',
            name='image2',
            field=models.ImageField(null=True, upload_to='contracts'),
        ),
        migrations.AddField(
            model_name='contract',
            name='image3',
            field=models.ImageField(null=True, upload_to='contracts'),
        ),
        migrations.DeleteModel(
            name='ContractImage',
        ),
    ]
