# Generated by Django 4.1.3 on 2022-11-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_treereport_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='treereport',
            name='address',
        ),
        migrations.AddField(
            model_name='treereport',
            name='address_lat',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='treereport',
            name='address_lng',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
