# Generated by Django 4.1.3 on 2022-11-19 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_mapreport_name_mapreport_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treereport',
            name='address_lat',
        ),
        migrations.RemoveField(
            model_name='treereport',
            name='address_lng',
        ),
    ]
