# Generated by Django 4.1.3 on 2022-11-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_remove_treereport_address_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treereport',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='treereport',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.DeleteModel(
            name='MapReport',
        ),
    ]
